const category = [
  {
    children: ["Action", "Aventure"],
    status: "Hide",
    parent: "Action & Adventure ",
    type: "Action",
    icon: "https://i.ibb.co/qNCvxT0/dumbbell.png",
    __v: 0,
  },
  {
    children: ["Comic", "Novel"],
    status: "Hide",
    parent: "Comic Book & Graphic Novel",
    type: "Comic",
    icon: "https://i.postimg.cc/gjz1P7wx/beauty.png",
    __v: 0,
  },
  {
    children: ["Detective", "Mystery"],
    status: "Show",
    parent: "Detective and Mystery",
    type: "Detective",
    icon: "https://i.postimg.cc/QNqrnQBB/baby.png",
    __v: 0,
  },
  {
    children: ["Fantasy"],
    status: "Show",
    parent: "Fantasy",
    type: "Fantasy",
    icon: "https://i.ibb.co/rdY6zL0/cleaner.png",
    __v: 0,
  },
  {
    children: ["Historical Fiction"],
    status: "Show",
    parent: "Historical Fiction",
    type: "Historical",
    icon: "https://i.postimg.cc/0jVF5Cmc/cookie.png",
    __v: 0,
  },
  {
    children: ["Horror"],
    status: "Show",
    parent: "Horror",
    type: "Horrory",
    icon: "https://i.ibb.co/HT7c6VT/chips.png",
    __v: 0,
  },
  {
    children: ["Literary Fiction"],
    status: "Show",
    parent: "Literary Fiction",
    type: "Literary ",
    icon: "https://i.postimg.cc/rmLvfsMC/strawberry-jam-1.png",
    __v: 0,
  },
  {
    children: ["Romance"],
    status: "Show",
    parent: "Romance",
    type: "Romance",
    icon: "https://i.postimg.cc/mk09xvk4/chili-sauce.png",
    __v: 0,
  },
  {
    children: ["Science Fiction "],
    status: "Hide",
    parent: "Science Fiction ",
    type: "Science Fiction ",
    icon: "https://i.postimg.cc/mk09xvk4/chili-sauce.png",
    __v: 0,
  },
  {
    children: ["Suspense", "Thrillers"],
    status: "Hide",
    parent: "Suspense and Thrillers",
    type: "Suspense",
    icon: "https://i.postimg.cc/mk09xvk4/chili-sauce.png",
    __v: 0,
  },
  {
    children: ["Women Fiction"],
    status: "Hide",
    parent: "Women's Fiction",
    type: "Women",
    icon: "https://i.postimg.cc/mk09xvk4/chili-sauce.png",
    __v: 0,
  },
  {
    children: ["True Crime"],
    status: "Hide",
    parent: "True Crime",
    type: "True Crime",
    icon: "https://i.postimg.cc/mk09xvk4/chili-sauce.png",
    __v: 0,
  },
];

module.exports = category;
