const products = [
  {
    price: 9,
    discount: 10,
    tag: JSON.stringify(["action", "adventure"]),
    flashSale: false,
    status: "Show",
    title: "SanDisk Ultra 128GB SDXC",
    author: "SanDisk Ultra 128GB SDXC",
    slug: "SanDisk Ultra 128GB SDXC",
    parent: "Action and Adventure",
    children: "Adventure",
    image: "https://i.ibb.co/wshGkSy/lorem-ipsum-dolor-sit-amet-2.jpg",
    originalPrice: 10,
    unit: "72",
    quantity: 100,
    type: "Adventure",
    description:
      "Action and adventure books constantly have you on the edge of your seat with excitement, as your fave main character repeatedly finds themselves in high stakes situations. The protagonist has an ultimate goal to achieve.",
    __v: 0,
  },
  {
    price: 9,
    discount: 0,
    tag: JSON.stringify(["action", "adventure"]),
    flashSale: false,
    status: "Show",
    title: "SanDisk Ultra 128GB SDXC",
    author: "SanDisk Ultra 128GB SDXC",
    slug: "SanDisk Ultra 128GB SDXC",
    parent: "Action and Adventure",
    children: "Adventure",
    image: "https://i.ibb.co/wshGkSy/lorem-ipsum-dolor-sit-amet-2.jpg",
    originalPrice: 10,
    unit: "72",
    quantity: 100,
    type: "Adventure",
    description:
      "Action and adventure books constantly have you on the edge of your seat with excitement, as your fave main character repeatedly finds themselves in high stakes situations. The protagonist has an ultimate goal to achieve.",
    __v: 0,
  },
  {
    price: 14,
    discount: 0,
    tag: JSON.stringify(["action", "adventure"]),
    flashSale: false,
    status: "Show",
    title: "CAN USB FD Adapter (GC-CAN-USB-FD)",
    author: "CAN USB FD Adapter (GC-CAN-USB-FD)",
    slug: "CAN USB FD Adapter (GC-CAN-USB-FD)",
    parent: "Action and Adventure",
    children: "Adventure",
    image: "https://i.ibb.co/bgdwMzj/lorem-ipsum-dolor-sit-amet.jpg",
    originalPrice: 14,
    unit: "72",
    quantity: 100,
    type: "Adventure",
    description:
      "Action and adventure books constantly have you on the edge of your seat with excitement, as your fave main character repeatedly finds themselves in high stakes situations. The protagonist has an ultimate goal to achieve.",
    __v: 0,
  },
  {
    price: 12,
    discount: 20,
    tag: JSON.stringify(["action", "adventure"]),
    flashSale: false,
    status: "Show",
    title: "TCHARMOUNT Full Motion TV Wall Mount Swivel",
    author: "CHARMOUNT Full Motion TV Wall Mount Swivel",
    slug: "CHARMOUNT Full Motion TV Wall Mount Swivel",
    parent: "Action and Adventure",
    children: "Adventure",
    image: "https://i.ibb.co/CJ9fvRF/piscing-elitt-amet-ipiscing-1.jpg",
    originalPrice: 15,
    unit: "20",
    quantity: 10,
    type: "Adventure",
    description:
      "Action and adventure books constantly have you on the edge of your seat with excitement, as your fave main character repeatedly finds themselves in high stakes situations. The protagonist has an ultimate goal to achieve.",
    __v: 0,
  },
  {
    price: 12,
    discount: 0,
    tag: JSON.stringify(["action", "adventure"]),
    flashSale: false,
    status: "Show",
    title: "TCHARMOUNT Full Motion TV Wall Mount Swivel",
    author: "CHARMOUNT Full Motion TV Wall Mount Swivel",
    slug: "CHARMOUNT Full Motion TV Wall Mount Swivel",
    parent: "Action and Adventure",
    children: "Adventure",
    image: "https://i.ibb.co/CJ9fvRF/piscing-elitt-amet-ipiscing-1.jpg",
    originalPrice: 15,
    unit: "20",
    quantity: 10,
    type: "Adventure",
    description:
      "Action and adventure books constantly have you on the edge of your seat with excitement, as your fave main character repeatedly finds themselves in high stakes situations. The protagonist has an ultimate goal to achieve.",
    __v: 0,
  },
  {
    price: 12,
    discount: 0,
    tag: JSON.stringify(["classics"]),
    flashSale: false,
    status: "Show",
    title: "Bose QuietComfort 35 II Wireless Bluetooth Headphones",
    author: "Bose QuietComfort 35 II Wireless Bluetooth Headphones",
    slug: "Bose QuietComfort 35 II Wireless Bluetooth Headphones",
    parent: "Classics",
    children: "classics",
    image: "https://i.ibb.co/1zv88Gy/piscing-elitt-amet-ipiscing.jpg",
    originalPrice: 12,
    unit: "100g",
    quantity: 100,
    type: "Classics",
    description:
      "You may think of these books as the throwback readings you were assigned in English class. (Looking at you, Charles Dickens.) The classics have been around for decades, and were often groundbreaking stories at their publish time, but have continued to be impactful for generations, serving as the foundation for many popular works we.",
    __v: 0,
  },
  {
    price: 11,
    discount: 15,
    tag: JSON.stringify(["classics"]),
    flashSale: false,
    status: "Show",
    title: "Apple AirPods with Charging Case (Wired)",
    author: "Apple AirPods with Charging Case (Wired)",
    slug: "Apple AirPods with Charging Case (Wired)",
    parent: "Classics",
    children: "classics",
    image: "https://i.ibb.co/b6xrcj5/rutrum-vel-imperdiet-eget-2.jpg",
    originalPrice: 13,
    unit: "100g",
    quantity: 100,
    type: "Classics",
    description:
      "You may think of these books as the throwback readings you were assigned in English class. (Looking at you, Charles Dickens.) The classics have been around for decades, and were often groundbreaking stories at their publish time, but have continued to be impactful for generations, serving as the foundation for many popular works we.",
    __v: 0,
  },
  {
    price: 11,
    discount: 0,
    tag: JSON.stringify(["classics"]),
    flashSale: false,
    status: "Show",
    title: "Apple AirPods with Charging Case (Wired)",
    author: "Apple AirPods with Charging Case (Wired)",
    slug: "Apple AirPods with Charging Case (Wired)",
    parent: "Classics",
    children: "classics",
    image: "https://i.ibb.co/b6xrcj5/rutrum-vel-imperdiet-eget-2.jpg",
    originalPrice: 13,
    unit: "100g",
    quantity: 100,
    type: "Classics",
    description:
      "You may think of these books as the throwback readings you were assigned in English class. (Looking at you, Charles Dickens.) The classics have been around for decades, and were often groundbreaking stories at their publish time, but have continued to be impactful for generations, serving as the foundation for many popular works we.",
    __v: 0,
  },
  {
    price: 12,
    discount: 0,
    tag: JSON.stringify(["classics"]),
    flashSale: false,
    status: "Show",
    title: "Cable Boom Micrntrol for Playstation PS4 laptop or Xbox",
    author: "Cable Boom Micrntrol for Playstation PS4 laptop or Xbox",
    slug: "Cable Boom Micrntrol for Playstation PS4 laptop or Xbox",
    parent: "Classics",
    children: "classics",
    image: "https://i.ibb.co/QKH3mmL/rutrum-vel-imperdiet-eget-4.jpg",
    originalPrice: 12,
    unit: "100g",
    quantity: 100,
    type: "Classics",
    description:
      "You may think of these books as the throwback readings you were assigned in English class. (Looking at you, Charles Dickens.) The classics have been around for decades, and were often groundbreaking stories at their publish time, but have continued to be impactful for generations, serving as the foundation for many popular works we.",
    __v: 0,
  },
  {
    price: 8,
    discount: 10,
    tag: JSON.stringify(["Comic Book", "Graphic Novel"]),
    flashSale: false,
    status: "Show",
    title: "Nikon D3500 W/ AF-P DX NIKKOR 18-55mm",
    author: "Nikon D3500 W/ AF-P DX NIKKOR 18-55mm",
    slug: "Nikon D3500 W/ AF-P DX NIKKOR 18-55mm",
    parent: "Comic Book",
    children: "Comic",
    image: "https://i.ibb.co/mTD557x/consectetuer-adipi-eget-1.jpg",
    originalPrice: 9,
    unit: "36pcs",
    quantity: 100,
    type: "Comic Book",
    description:
      "The stories in comic books and graphic novels are presented to the reader through engaging, sequential narrative art (illustrations and typography) that's either presented in a specific design or the traditional panel layout you find in comics. With both, you'll often find the dialogue presented in the tell-tale",
    __v: 0,
  },
  {
    price: 8,
    discount: 0,
    tag: JSON.stringify(["Comic Book", "Graphic Novel"]),
    flashSale: false,
    status: "Show",
    title: "Nikon D3500 W/ AF-P DX NIKKOR 18-55mm",
    author: "Nikon D3500 W/ AF-P DX NIKKOR 18-55mm",
    slug: "Nikon D3500 W/ AF-P DX NIKKOR 18-55mm",
    parent: "Comic Book",
    children: "Comic",
    image: "https://i.ibb.co/mTD557x/consectetuer-adipi-eget-1.jpg",
    originalPrice: 9,
    unit: "36pcs",
    quantity: 100,
    type: "Comic Book",
    description:
      "The stories in comic books and graphic novels are presented to the reader through engaging, sequential narrative art (illustrations and typography) that's either presented in a specific design or the traditional panel layout you find in comics. With both, you'll often find the dialogue presented in the tell-tale",
    __v: 0,
  },
  {
    price: 12,
    discount: 20,
    tag: JSON.stringify(["Comic Book", "Graphic Novel"]),
    flashSale: false,
    status: "Show",
    title: "Apple MacBook Air",
    author: "Apple MacBook Air",
    slug: "Apple MacBook Air",
    parent: "Comic Book",
    children: "Comic",
    image: "https://i.ibb.co/qW3cXyx/donec-odio-sit-amet-ipisci-1.jpg",
    originalPrice: 15,
    unit: "36pcs",
    quantity: 100,
    type: "Comic Book",
    description:
      "The stories in comic books and graphic novels are presented to the reader through engaging, sequential narrative art (illustrations and typography) that's either presented in a specific design or the traditional panel layout you find in comics. With both, you'll often find the dialogue presented in the tell-tale",
    __v: 0,
  },
  {
    price: 22,
    discount: 0,
    tag: JSON.stringify(["Comic Book", "Graphic Novel"]),
    flashSale: false,
    status: "Show",
    title: "Kauffman Orchards",
    author: "Kauffman Orchards",
    slug: "Kauffman Orchards",
    parent: "Comic Book",
    children: "Comic",
    image: "https://i.ibb.co/gJhF5Kk/ipiscing-elit-odio-sit-amet-1.jpg",
    originalPrice: 22,
    unit: "36pcs",
    quantity: 100,
    type: "Comic Book",
    description:
      "The stories in comic books and graphic novels are presented to the reader through engaging, sequential narrative art (illustrations and typography) that's either presented in a specific design or the traditional panel layout you find in comics. With both, you'll often find the dialogue presented in the tell-tale",
    __v: 0,
  },
  {
    price: 7,
    discount: 11,
    tag: JSON.stringify(["Detective", " Mystery"]),
    flashSale: false,
    status: "Show",
    title: "Homegrown McIntosh Apples",
    author: "Homegrown McIntosh Apples",
    slug: "Michael connelly",
    parent: "Detective and Mystery",
    children: "Detective",
    image: "https://i.ibb.co/HxLVfyk/lorem-ipsum-dolor-sit-amet-1.jpg",
    originalPrice: 8,
    unit: "24pcs",
    quantity: 99,
    type: "Detective and Mystery",
    description:
      "Baby Products are products intended to be used on infants and children under the age of three. Baby products are specially formulated to be mild and non-irritating and use ingredients that are selected for these properties. Baby products include baby shampoos and baby lotions, oils, powders and creams.",
    __v: 0,
  },
 {
    price: 7,
    discount: 0,
    tag: JSON.stringify(["Detective", " Mystery"]),
    flashSale: false,
    status: "Show",
    title: "Homegrown McIntosh Apples",
    author: "Homegrown McIntosh Apples",
    slug: "Michael connelly",
    parent: "Detective and Mystery",
    children: "Detective",
    image: "https://i.ibb.co/HxLVfyk/lorem-ipsum-dolor-sit-amet-1.jpg",
    originalPrice: 8,
    unit: "24pcs",
    quantity: 99,
    type: "Detective and Mystery",
    description:
      "Baby Products are products intended to be used on infants and children under the age of three. Baby products are specially formulated to be mild and non-irritating and use ingredients that are selected for these properties. Baby products include baby shampoos and baby lotions, oils, powders and creams.",
    __v: 0,
  },

  {
    price: 9,
    discount: 10,
    tag: JSON.stringify(["action", "adventure"]),
    flashSale: false,
    status: "Show",
    title: "SanDisk Ultra 128GB SDXC",
    author: "SanDisk Ultra 128GB SDXC",
    slug: "SanDisk Ultra 128GB SDXC",
    parent: "Action and Adventure",
    children: "Adventure",
    image: "https://i.ibb.co/wshGkSy/lorem-ipsum-dolor-sit-amet-2.jpg",
    originalPrice: 10,
    unit: "72",
    quantity: 100,
    type: "Adventure",
    description:
      "Action and adventure books constantly have you on the edge of your seat with excitement, as your fave main character repeatedly finds themselves in high stakes situations. The protagonist has an ultimate goal to achieve.",
    __v: 0,
  },
  {
    price: 9,
    discount: 0,
    tag: JSON.stringify(["action", "adventure"]),
    flashSale: false,
    status: "Show",
    title: "SanDisk Ultra 128GB SDXC",
    author: "SanDisk Ultra 128GB SDXC",
    slug: "SanDisk Ultra 128GB SDXC",
    parent: "Action and Adventure",
    children: "Adventure",
    image: "https://i.ibb.co/wshGkSy/lorem-ipsum-dolor-sit-amet-2.jpg",
    originalPrice: 10,
    unit: "72",
    quantity: 100,
    type: "Adventure",
    description:
      "Action and adventure books constantly have you on the edge of your seat with excitement, as your fave main character repeatedly finds themselves in high stakes situations. The protagonist has an ultimate goal to achieve.",
    __v: 0,
  },
  {
    price: 14,
    discount: 0,
    tag: JSON.stringify(["action", "adventure"]),
    flashSale: false,
    status: "Show",
    title: "CAN USB FD Adapter (GC-CAN-USB-FD)",
    author: "CAN USB FD Adapter (GC-CAN-USB-FD)",
    slug: "CAN USB FD Adapter (GC-CAN-USB-FD)",
    parent: "Action and Adventure",
    children: "Adventure",
    image: "https://i.ibb.co/bgdwMzj/lorem-ipsum-dolor-sit-amet.jpg",
    originalPrice: 14,
    unit: "72",
    quantity: 100,
    type: "Adventure",
    description:
      "Action and adventure books constantly have you on the edge of your seat with excitement, as your fave main character repeatedly finds themselves in high stakes situations. The protagonist has an ultimate goal to achieve.",
    __v: 0,
  },
  {
    price: 12,
    discount: 20,
    tag: JSON.stringify(["action", "adventure"]),
    flashSale: false,
    status: "Show",
    title: "TCHARMOUNT Full Motion TV Wall Mount Swivel",
    author: "CHARMOUNT Full Motion TV Wall Mount Swivel",
    slug: "CHARMOUNT Full Motion TV Wall Mount Swivel",
    parent: "Action and Adventure",
    children: "Adventure",
    image: "https://i.ibb.co/CJ9fvRF/piscing-elitt-amet-ipiscing-1.jpg",
    originalPrice: 15,
    unit: "20",
    quantity: 10,
    type: "Adventure",
    description:
      "Action and adventure books constantly have you on the edge of your seat with excitement, as your fave main character repeatedly finds themselves in high stakes situations. The protagonist has an ultimate goal to achieve.",
    __v: 0,
  },
  {
    price: 12,
    discount: 0,
    tag: JSON.stringify(["classics"]),
    flashSale: false,
    status: "Show",
    title: "Bose QuietComfort 35 II Wireless Bluetooth Headphones",
    author: "Bose QuietComfort 35 II Wireless Bluetooth Headphones",
    slug: "Bose QuietComfort 35 II Wireless Bluetooth Headphones",
    parent: "Classics",
    children: "classics",
    image: "https://i.ibb.co/1zv88Gy/piscing-elitt-amet-ipiscing.jpg",
    originalPrice: 12,
    unit: "100g",
    quantity: 100,
    type: "Classics",
    description:
      "You may think of these books as the throwback readings you were assigned in English class. (Looking at you, Charles Dickens.) The classics have been around for decades, and were often groundbreaking stories at their publish time, but have continued to be impactful for generations, serving as the foundation for many popular works we.",
    __v: 0,
  },
  {
    price: 11,
    discount: 15,
    tag: JSON.stringify(["classics"]),
    flashSale: false,
    status: "Show",
    title: "Apple AirPods with Charging Case (Wired)",
    author: "Apple AirPods with Charging Case (Wired)",
    slug: "Apple AirPods with Charging Case (Wired)",
    parent: "Classics",
    children: "classics",
    image: "https://i.ibb.co/b6xrcj5/rutrum-vel-imperdiet-eget-2.jpg",
    originalPrice: 13,
    unit: "100g",
    quantity: 100,
    type: "Classics",
    description:
      "You may think of these books as the throwback readings you were assigned in English class. (Looking at you, Charles Dickens.) The classics have been around for decades, and were often groundbreaking stories at their publish time, but have continued to be impactful for generations, serving as the foundation for many popular works we.",
    __v: 0,
  },
  {
    price: 12,
    discount: 0,
    tag: JSON.stringify(["classics"]),
    flashSale: false,
    status: "Show",
    title: "Cable Boom Micrntrol for Playstation PS4 laptop or Xbox",
    author: "Cable Boom Micrntrol for Playstation PS4 laptop or Xbox",
    slug: "Cable Boom Micrntrol for Playstation PS4 laptop or Xbox",
    parent: "Classics",
    children: "classics",
    image: "https://i.ibb.co/QKH3mmL/rutrum-vel-imperdiet-eget-4.jpg",
    originalPrice: 12,
    unit: "100g",
    quantity: 100,
    type: "Classics",
    description:
      "You may think of these books as the throwback readings you were assigned in English class. (Looking at you, Charles Dickens.) The classics have been around for decades, and were often groundbreaking stories at their publish time, but have continued to be impactful for generations, serving as the foundation for many popular works we.",
    __v: 0,
  },
  {
    price: 8,
    discount: 10,
    tag: JSON.stringify(["Comic Book", "Graphic Novel"]),
    flashSale: false,
    status: "Show",
    title: "Nikon D3500 W/ AF-P DX NIKKOR 18-55mm",
    author: "Nikon D3500 W/ AF-P DX NIKKOR 18-55mm",
    slug: "Nikon D3500 W/ AF-P DX NIKKOR 18-55mm",
    parent: "Comic Book",
    children: "Comic",
    image: "https://i.ibb.co/mTD557x/consectetuer-adipi-eget-1.jpg",
    originalPrice: 9,
    unit: "36pcs",
    quantity: 100,
    type: "Comic Book",
    description:
      "The stories in comic books and graphic novels are presented to the reader through engaging, sequential narrative art (illustrations and typography) that's either presented in a specific design or the traditional panel layout you find in comics. With both, you'll often find the dialogue presented in the tell-tale",
    __v: 0,
  },
  {
    price: 12,
    discount: 20,
    tag: JSON.stringify(["Comic Book", "Graphic Novel"]),
    flashSale: false,
    status: "Show",
    title: "Apple MacBook Air",
    author: "Apple MacBook Air",
    slug: "Apple MacBook Air",
    parent: "Comic Book",
    children: "Comic",
    image: "https://i.ibb.co/qW3cXyx/donec-odio-sit-amet-ipisci-1.jpg",
    originalPrice: 15,
    unit: "36pcs",
    quantity: 100,
    type: "Comic Book",
    description:
      "The stories in comic books and graphic novels are presented to the reader through engaging, sequential narrative art (illustrations and typography) that's either presented in a specific design or the traditional panel layout you find in comics. With both, you'll often find the dialogue presented in the tell-tale",
    __v: 0,
  },
  {
    price: 22,
    discount: 0,
    tag: JSON.stringify(["Comic Book", "Graphic Novel"]),
    flashSale: false,
    status: "Show",
    title: "Kauffman Orchards",
    author: "Kauffman Orchards",
    slug: "Kauffman Orchards",
    parent: "Comic Book",
    children: "Comic",
    image: "https://i.ibb.co/gJhF5Kk/ipiscing-elit-odio-sit-amet-1.jpg",
    originalPrice: 22,
    unit: "36pcs",
    quantity: 100,
    type: "Comic Book",
    description:
      "The stories in comic books and graphic novels are presented to the reader through engaging, sequential narrative art (illustrations and typography) that's either presented in a specific design or the traditional panel layout you find in comics. With both, you'll often find the dialogue presented in the tell-tale",
    __v: 0,
  },
  {
    price: 7,
    discount: 11,
    tag: JSON.stringify(["Detective", " Mystery"]),
    flashSale: false,
    status: "Show",
    title: "Homegrown McIntosh Apples",
    author: "Homegrown McIntosh Apples",
    slug: "Michael connelly",
    parent: "Detective and Mystery",
    children: "Detective",
    image: "https://i.ibb.co/HxLVfyk/lorem-ipsum-dolor-sit-amet-1.jpg",
    originalPrice: 8,
    unit: "24pcs",
    quantity: 99,
    type: "Detective and Mystery",
    description:
      "Baby Products are products intended to be used on infants and children under the age of three. Baby products are specially formulated to be mild and non-irritating and use ingredients that are selected for these properties. Baby products include baby shampoos and baby lotions, oils, powders and creams.",
    __v: 0,
  },
 
];

module.exports = products;
